"""Add archived column to taxes table

Revision ID: 018a9ad5a207
Revises: 55c4c8d9930b
Create Date: 2025-08-21 11:17:43.640535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '018a9ad5a207'
down_revision: Union[str, Sequence[str], None] = '55c4c8d9930b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Corrected upgrade to add the 'archived' column to the 'taxes' table."""
    # ### commands auto generated by Alembic - this is a corrected version ###
    with op.batch_alter_table('taxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Corrected downgrade to remove the 'archived' column from the 'taxes' table."""
    # ### commands auto generated by Alembic - this is a corrected version ###
    with op.batch_alter_table('taxes', schema=None) as batch_op:
        batch_op.drop_column('archived')
    # ### end Alembic commands ###
