"""add_comprehensive_billing_models

Revision ID: 7d4c92c497d0
Revises: c5d8e9f0a1b2
Create Date: 2025-08-28 08:49:50.721391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d4c92c497d0'
down_revision: Union[str, Sequence[str], None] = 'c5d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cycle_type', sa.String(length=20), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=True),
    sa.Column('billing_day_type', sa.String(length=20), nullable=True),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('prorate_first_bill', sa.Boolean(), nullable=True),
    sa.Column('prorate_last_bill', sa.Boolean(), nullable=True),
    sa.Column('proration_method', sa.String(length=20), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('due_date_type', sa.String(length=20), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.Column('late_fee_type', sa.String(length=20), nullable=True),
    sa.Column('late_fee_amount', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('billing_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_cycles_id'), ['id'], unique=False)

    op.create_table('billing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_events_id'), ['id'], unique=False)

    op.create_table('customer_billing_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('billing_cycle_id', sa.Integer(), nullable=False),
    sa.Column('custom_billing_day', sa.Integer(), nullable=True),
    sa.Column('invoice_delivery_method', sa.String(length=20), nullable=True),
    sa.Column('invoice_format', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('preferred_payment_method_id', sa.Integer(), nullable=True),
    sa.Column('auto_payment_enabled', sa.Boolean(), nullable=True),
    sa.Column('credit_limit', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('dunning_enabled', sa.Boolean(), nullable=True),
    sa.Column('tax_exempt', sa.Boolean(), nullable=True),
    sa.Column('tax_exempt_reason', sa.String(length=255), nullable=True),
    sa.Column('tax_exempt_certificate', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['billing_cycle_id'], ['billing_cycles.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['preferred_payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    with op.batch_alter_table('customer_billing_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_billing_configs_id'), ['id'], unique=False)

    op.create_table('usage_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('usage_type', sa.String(length=20), nullable=False),
    sa.Column('usage_amount', sa.DECIMAL(precision=15, scale=6), nullable=False),
    sa.Column('usage_unit', sa.String(length=10), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=True),
    sa.Column('rate_per_unit', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('billing_period', sa.String(length=7), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_tracking', schema=None) as batch_op:
        batch_op.create_index('idx_usage_billing_period', ['billing_period'], unique=False)
        batch_op.create_index('idx_usage_customer_date', ['customer_id', 'usage_date'], unique=False)
        batch_op.create_index('idx_usage_service', ['service_type', 'service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_tracking_id'), ['id'], unique=False)

    with op.batch_alter_table('taxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurisdiction_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tax_authority', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('minimum_taxable_amount', sa.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('maximum_tax_amount', sa.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('effective_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('applicable_service_types', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('exempt_service_types', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('applicable_customer_categories', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('exempt_customer_categories', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('compound_with_tax_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('compound_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('compound_order')
        batch_op.drop_column('compound_with_tax_ids')
        batch_op.drop_column('exempt_customer_categories')
        batch_op.drop_column('applicable_customer_categories')
        batch_op.drop_column('exempt_service_types')
        batch_op.drop_column('applicable_service_types')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('effective_date')
        batch_op.drop_column('maximum_tax_amount')
        batch_op.drop_column('minimum_taxable_amount')
        batch_op.drop_column('tax_authority')
        batch_op.drop_column('jurisdiction_code')

    with op.batch_alter_table('usage_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_tracking_id'))
        batch_op.drop_index('idx_usage_service')
        batch_op.drop_index('idx_usage_customer_date')
        batch_op.drop_index('idx_usage_billing_period')

    op.drop_table('usage_tracking')
    with op.batch_alter_table('customer_billing_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_billing_configs_id'))

    op.drop_table('customer_billing_configs')
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_events_id'))

    op.drop_table('billing_events')
    with op.batch_alter_table('billing_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_cycles_id'))

    op.drop_table('billing_cycles')
    # ### end Alembic commands ###
