"""add payment_gateways table

Revision ID: 82f90642c54c
Revises: 9da0a0ad1dbd
Create Date: 2025-09-12 11:02:45.207275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82f90642c54c'
down_revision: Union[str, Sequence[str], None] = '9da0a0ad1dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_secret', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('payment_gateways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_gateways_id'), ['id'], unique=False)

    with op.batch_alter_table('customer_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_statistics_id'))

    op.drop_table('customer_statistics')
    with op.batch_alter_table('radius_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radius_sessions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_radius_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_radius_sessions_login'))
        batch_op.drop_index(batch_op.f('ix_radius_sessions_service_id'))
        batch_op.drop_index(batch_op.f('ix_radius_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_radius_sessions_session_status'))

    op.drop_table('radius_sessions')
    with op.batch_alter_table('customers_online', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_online_id'))

    op.drop_table('customers_online')
    with op.batch_alter_table('nas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nas_nasname'))

    op.drop_table('nas')
    with op.batch_alter_table('bundle_tariffs', schema=None) as batch_op:
        batch_op.alter_column('hide_on_admin_portal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('show_on_customer_portal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('message_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'file_storage', ['generated_file_id'], ['id'])

    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.alter_column('acctsessionid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('acctuniqueid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('acctsessiontime',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('acctterminatecause',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('radacct_active_session_idx'), postgresql_where='(acctstoptime IS NULL)')
        batch_op.drop_index(batch_op.f('radacct_bulk_close'), postgresql_where='(acctstoptime IS NULL)')
        batch_op.drop_index(batch_op.f('radacct_calss_idx'))
        batch_op.drop_index(batch_op.f('radacct_start_user_idx'))
        batch_op.create_index(batch_op.f('ix_radacct_acctsessionid'), ['acctsessionid'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_username'), ['username'], unique=False)
        batch_op.drop_column('framedipv6address')
        batch_op.drop_column('delegatedipv6prefix')
        batch_op.drop_column('realm')
        batch_op.drop_column('framedipv6prefix')
        batch_op.drop_column('acctupdatetime')
        batch_op.drop_column('nasporttype')
        batch_op.drop_column('framedprotocol')
        batch_op.drop_column('servicetype')
        batch_op.drop_column('calledstationid')
        batch_op.drop_column('class')
        batch_op.drop_column('acctauthentic')
        batch_op.drop_column('callingstationid')
        batch_op.drop_column('nasportid')
        batch_op.drop_column('connectinfo_start')
        batch_op.drop_column('connectinfo_stop')
        batch_op.drop_column('framedinterfaceid')
        batch_op.drop_column('acctinterval')

    with op.batch_alter_table('radcheck', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('attribute',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=253),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.drop_index(batch_op.f('radcheck_username'))
        batch_op.create_index(batch_op.f('ix_radcheck_username'), ['username'], unique=False)

    with op.batch_alter_table('radgroupcheck', schema=None) as batch_op:
        batch_op.alter_column('groupname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('attribute',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=253),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.drop_index(batch_op.f('radgroupcheck_groupname'))
        batch_op.create_index(batch_op.f('ix_radgroupcheck_groupname'), ['groupname'], unique=False)

    with op.batch_alter_table('radgroupreply', schema=None) as batch_op:
        batch_op.alter_column('groupname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('attribute',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=253),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.drop_index(batch_op.f('radgroupreply_groupname'))
        batch_op.create_index(batch_op.f('ix_radgroupreply_groupname'), ['groupname'], unique=False)

    with op.batch_alter_table('radpostauth', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('pass',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('reply',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
        batch_op.drop_index(batch_op.f('radpostauth_class_idx'))
        batch_op.drop_index(batch_op.f('radpostauth_username_idx'))
        batch_op.create_index(batch_op.f('ix_radpostauth_username'), ['username'], unique=False)
        batch_op.drop_column('class')
        batch_op.drop_column('calledstationid')
        batch_op.drop_column('callingstationid')

    with op.batch_alter_table('radreply', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('attribute',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=253),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.drop_index(batch_op.f('radreply_username'))
        batch_op.create_index(batch_op.f('ix_radreply_username'), ['username'], unique=False)

    with op.batch_alter_table('radusergroup', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('groupname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.drop_index(batch_op.f('radusergroup_username'))
        batch_op.create_index(batch_op.f('ix_radusergroup_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radusergroup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radusergroup_username'))
        batch_op.create_index(batch_op.f('radusergroup_username'), ['username'], unique=False)
        batch_op.alter_column('groupname',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))

    with op.batch_alter_table('radreply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radreply_username'))
        batch_op.create_index(batch_op.f('radreply_username'), ['username', 'attribute'], unique=False)
        batch_op.alter_column('value',
               existing_type=sa.String(length=253),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('attribute',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))

    with op.batch_alter_table('radpostauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('callingstationid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('calledstationid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('class', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_radpostauth_username'))
        batch_op.create_index(batch_op.f('radpostauth_username_idx'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('radpostauth_class_idx'), ['class'], unique=False)
        batch_op.alter_column('reply',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('pass',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('radgroupreply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radgroupreply_groupname'))
        batch_op.create_index(batch_op.f('radgroupreply_groupname'), ['groupname', 'attribute'], unique=False)
        batch_op.alter_column('value',
               existing_type=sa.String(length=253),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('attribute',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('groupname',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))

    with op.batch_alter_table('radgroupcheck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radgroupcheck_groupname'))
        batch_op.create_index(batch_op.f('radgroupcheck_groupname'), ['groupname', 'attribute'], unique=False)
        batch_op.alter_column('value',
               existing_type=sa.String(length=253),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('attribute',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('groupname',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))

    with op.batch_alter_table('radcheck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radcheck_username'))
        batch_op.create_index(batch_op.f('radcheck_username'), ['username', 'attribute'], unique=False)
        batch_op.alter_column('value',
               existing_type=sa.String(length=253),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('attribute',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))

    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acctinterval', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('framedinterfaceid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('connectinfo_stop', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('connectinfo_start', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nasportid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('callingstationid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acctauthentic', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('class', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('calledstationid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('servicetype', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('framedprotocol', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nasporttype', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acctupdatetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('framedipv6prefix', postgresql.INET(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('realm', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delegatedipv6prefix', postgresql.INET(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('framedipv6address', postgresql.INET(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_radacct_username'))
        batch_op.drop_index(batch_op.f('ix_radacct_acctsessionid'))
        batch_op.create_index(batch_op.f('radacct_start_user_idx'), ['acctstarttime', 'username'], unique=False)
        batch_op.create_index(batch_op.f('radacct_calss_idx'), ['class'], unique=False)
        batch_op.create_index(batch_op.f('radacct_bulk_close'), ['nasipaddress', 'acctstarttime'], unique=False, postgresql_where='(acctstoptime IS NULL)')
        batch_op.create_index(batch_op.f('radacct_active_session_idx'), ['acctuniqueid'], unique=False, postgresql_where='(acctstoptime IS NULL)')
        batch_op.alter_column('acctterminatecause',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('acctsessiontime',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('acctuniqueid',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('acctsessionid',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('message_queue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('generated_file_id')

    with op.batch_alter_table('bundle_tariffs', schema=None) as batch_op:
        batch_op.alter_column('show_on_customer_portal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('hide_on_admin_portal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    op.create_table('nas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nasname', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('shortname', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=30), server_default=sa.text("'other'::character varying"), autoincrement=False, nullable=True),
    sa.Column('ports', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('secret', sa.VARCHAR(length=60), server_default=sa.text("'secret'::character varying"), autoincrement=False, nullable=False),
    sa.Column('server', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('community', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nas_pkey'))
    )
    with op.batch_alter_table('nas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nas_nasname'), ['nasname'], unique=False)

    op.create_table('customers_online',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tariff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nas_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('login', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username_real', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('in_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('out_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('start_session', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ipv4', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('ipv6', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('mac', sa.VARCHAR(length=17), autoincrement=False, nullable=True),
    sa.Column('call_to', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('port', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('time_on', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_change', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('login_is', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('customers_online_customer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('customers_online_partner_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['internet_services.id'], name=op.f('customers_online_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_online_pkey'))
    )
    with op.batch_alter_table('customers_online', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_online_id'), ['id'], unique=False)

    op.create_table('radius_sessions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tariff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nas_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('login', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username_real', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('in_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('out_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('start_session', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('end_session', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ipv4', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('ipv6', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('mac', sa.VARCHAR(length=17), autoincrement=False, nullable=True),
    sa.Column('call_to', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('port', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('time_on', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_change', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('login_is', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('session_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('terminate_cause', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('radius_sessions_customer_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nas_id'], ['routers.id'], name=op.f('radius_sessions_nas_id_fkey')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('radius_sessions_partner_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['internet_services.id'], name=op.f('radius_sessions_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('radius_sessions_pkey'))
    )
    with op.batch_alter_table('radius_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radius_sessions_session_status'), ['session_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_radius_sessions_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_radius_sessions_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radius_sessions_login'), ['login'], unique=False)
        batch_op.create_index(batch_op.f('ix_radius_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radius_sessions_customer_id'), ['customer_id'], unique=False)

    op.create_table('customer_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tariff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nas_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('login', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('in_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('out_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('ipv4', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('ipv6', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('mac', sa.VARCHAR(length=17), autoincrement=False, nullable=True),
    sa.Column('call_to', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('port', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_repeat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('terminate_cause', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('customer_statistics_customer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_statistics_pkey'))
    )
    with op.batch_alter_table('customer_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_statistics_id'), ['id'], unique=False)

    with op.batch_alter_table('payment_gateways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_gateways_id'))

    op.drop_table('payment_gateways')
    # ### end Alembic commands ###
