"""Add billing_due column to customer_billing table

Revision ID: 8341a9634492
Revises: 018a9ad5a207
Create Date: 2025-08-21 11:29:33.491186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8341a9634492'
down_revision: Union[str, Sequence[str], None] = '018a9ad5a207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Corrected upgrade to add the 'billing_due' column to the 'customer_billing' table."""
    # ### commands auto generated by Alembic - this is a corrected version ###
    with op.batch_alter_table('customer_billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_due', sa.Integer(), server_default=sa.text('14'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Corrected downgrade to remove the 'billing_due' column from the 'customer_billing' table."""
    # ### commands auto generated by Alembic - this is a corrected version ###
    with op.batch_alter_table('customer_billing', schema=None) as batch_op:
        batch_op.drop_column('billing_due')
    # ### end Alembic commands ###
