"""add_customer_portal_visibility_fields_to_bundle_tariffs

Revision ID: 8e5d9a1b2c3f
Revises: 7d4c92c497d0
Create Date: 2025-08-29 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5d9a1b2c3f'
down_revision: Union[str, Sequence[str], None] = '7d4c92c497d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle_tariffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_on_admin_portal', sa.Boolean(), nullable=True, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('show_on_customer_portal', sa.Boolean(), nullable=True, server_default=sa.text('false')))

    # Set default values for existing rows
    op.execute("UPDATE bundle_tariffs SET hide_on_admin_portal = false WHERE hide_on_admin_portal IS NULL")
    op.execute("UPDATE bundle_tariffs SET show_on_customer_portal = false WHERE show_on_customer_portal IS NULL")

    # Make columns non-nullable after setting defaults
    with op.batch_alter_table('bundle_tariffs', schema=None) as batch_op:
        batch_op.alter_column('hide_on_admin_portal', nullable=False)
        batch_op.alter_column('show_on_customer_portal', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle_tariffs', schema=None) as batch_op:
        batch_op.drop_column('show_on_customer_portal')
        batch_op.drop_column('hide_on_admin_portal')
    # ### end Alembic commands ###