"""Add device_id and relationship to SNMPMonitoringProfile

Revision ID: 9f1f5b773d27
Revises: 1a2b3c4d5e6f
Create Date: 2025-09-18 11:18:10.386918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f1f5b773d27'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nas_nasname_idx'))
        batch_op.drop_index(batch_op.f('nas_shortname_idx'))
        batch_op.create_index('nas_nasname', ['nasname'], unique=False)
        batch_op.create_unique_constraint(None, ['shortname'])

    with op.batch_alter_table('payment_gateways', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.create_index('radacct_active_session_idx', ['acctuniqueid'], unique=False, postgresql_where=sa.text('acctstoptime IS NULL'))
        batch_op.drop_column('servicetype')
        batch_op.drop_column('callingstationid')
        batch_op.drop_column('acctupdatetime')
        batch_op.drop_column('acctauthentic')
        batch_op.drop_column('realm')
        batch_op.drop_column('framedinterfaceid')
        batch_op.drop_column('connectinfo_stop')
        batch_op.drop_column('nasportid')
        batch_op.drop_column('nasporttype')
        batch_op.drop_column('framedprotocol')
        batch_op.drop_column('acctinterval')
        batch_op.drop_column('connectinfo_start')
        batch_op.drop_column('delegatedipv6prefix')
        batch_op.drop_column('framedipv6address')
        batch_op.drop_column('class')
        batch_op.drop_column('calledstationid')
        batch_op.drop_column('framedipv6prefix')

    with op.batch_alter_table('snmp_monitoring_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'monitoring_devices', ['device_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snmp_monitoring_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('device_id')

    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('framedipv6prefix', postgresql.INET(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('calledstationid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('class', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('framedipv6address', postgresql.INET(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delegatedipv6prefix', postgresql.INET(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('connectinfo_start', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acctinterval', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('framedprotocol', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nasporttype', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nasportid', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('connectinfo_stop', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('framedinterfaceid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('realm', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acctauthentic', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acctupdatetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('callingstationid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('servicetype', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index('radacct_active_session_idx', postgresql_where=sa.text('acctstoptime IS NULL'))

    with op.batch_alter_table('payment_gateways', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('nas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('nas_nasname')
        batch_op.create_index(batch_op.f('nas_shortname_idx'), ['shortname'], unique=True)
        batch_op.create_index(batch_op.f('nas_nasname_idx'), ['nasname'], unique=False)

    # ### end Alembic commands ###
