"""Add realm column to radacct table

Revision ID: d0d9bbdbf537
Revises: 9f1f5b773d27
Create Date: 2025-09-24 12:04:46.460667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d9bbdbf537'
down_revision: Union[str, Sequence[str], None] = '9f1f5b773d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realm', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.drop_column('realm')

    # ### end Alembic commands ###
