"""Add remaining columns to customers

Revision ID: d3a2b1c0d4e5
Revises: 8cfcedd553ef
Create Date: 2025-08-19 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3a2b1c0d4e5'
down_revision: Union[str, Sequence[str], None] = '8cfcedd553ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=True))
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('email', postgresql.CITEXT(), nullable=True))
        batch_op.add_column(sa.Column('billing_email', postgresql.CITEXT(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=20), server_default='person', nullable=True))
        batch_op.add_column(sa.Column('street_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_type', sa.String(length=20), server_default='recurring', nullable=True))
        batch_op.add_column(sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_customers_location_id', 'locations', ['location_id'], ['id'])
        batch_op.create_foreign_key('fk_customers_partner_id', 'partners', ['partner_id'], ['id'])
        batch_op.create_foreign_key('fk_customers_parent_id', 'customers', ['parent_id'], ['id'])

    # Populate default values for new non-nullable foreign keys on existing rows
    op.execute("UPDATE customers SET partner_id = 1 WHERE partner_id IS NULL")
    op.execute("UPDATE customers SET location_id = 1 WHERE location_id IS NULL")

    # Now alter the columns to be non-nullable
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('partner_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('location_id', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_parent_id', type_='foreignkey')
        batch_op.drop_constraint('fk_customers_partner_id', type_='foreignkey')
        batch_op.drop_constraint('fk_customers_location_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_status'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('custom_fields')
        batch_op.drop_column('billing_type')
        batch_op.drop_column('city')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('street_1')
        batch_op.drop_column('category')
        batch_op.drop_column('phone')
        batch_op.drop_column('billing_email')
        batch_op.drop_column('email')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('location_id')
        batch_op.drop_column('partner_id')
        batch_op.drop_column('status')
    # ### end Alembic commands ###