"""Add all standard columns to radacct table

Revision ID: f7199efa0c6a
Revises: d0d9bbdbf537
Create Date: 2025-09-24 12:09:32.613325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7199efa0c6a'
down_revision: Union[str, Sequence[str], None] = 'd0d9bbdbf537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nasportid', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nasporttype', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('acctupdatetime', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('acctauthentic', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('connectinfo_start', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('connectinfo_stop', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calledstationid', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('callingstationid', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('servicetype', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('framedprotocol', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('framedipv6address', postgresql.INET(), nullable=True))
        batch_op.add_column(sa.Column('framedipv6prefix', postgresql.INET(), nullable=True))
        batch_op.add_column(sa.Column('framedinterfaceid', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delegatedipv6prefix', postgresql.INET(), nullable=True))
        batch_op.add_column(sa.Column('class', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.drop_column('class')
        batch_op.drop_column('delegatedipv6prefix')
        batch_op.drop_column('framedinterfaceid')
        batch_op.drop_column('framedipv6prefix')
        batch_op.drop_column('framedipv6address')
        batch_op.drop_column('framedprotocol')
        batch_op.drop_column('servicetype')
        batch_op.drop_column('callingstationid')
        batch_op.drop_column('calledstationid')
        batch_op.drop_column('connectinfo_stop')
        batch_op.drop_column('connectinfo_start')
        batch_op.drop_column('acctauthentic')
        batch_op.drop_column('acctupdatetime')
        batch_op.drop_column('nasporttype')
        batch_op.drop_column('nasportid')

    # ### end Alembic commands ###
